apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: reports-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: ghcr.io/kyverno/reports-controller
    newTag: v1.10.1@sha256:a6c8051b86584b836bcf94df1127b6afced97007255a5330c4599347b009fbdb
