apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: ghcr.io/kyverno/kyverno
    newTag: v1.10.1@sha256:2afab1a7bf3a73ddb5c7a89604b9daafef560214d65f526be17a6d7ae2c3693d
  - name: ghcr.io/kyverno/kyvernopre
    newTag: v1.10.0@sha256:81aa67584e1c71e83429f31fe1bc3c99550418639ba6e6735aea07bce9a4c7c8
