apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
replicas:
  - name: kyverno-admission-controller
    count: 2
images:
  - name: ghcr.io/kyverno/kyverno
    newTag: v1.14.4@sha256:39e6c358e16809eeb0ea517250a0c2295f6f76aed828e8406eca8e88c9e9f4b7
  - name: ghcr.io/kyverno/kyvernopre
    newTag: v1.14.4@sha256:352f39762501a32e0f29211294f27e6fced73e250a70018d97eee9f0b1a2c299
