apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
replicas:
  - name: kyverno-admission-controller
    count: 2
images:
  - name: ghcr.io/kyverno/kyverno
    newTag: v1.14.0@sha256:b63650f0876bb10d61d3592fa2310802108f2261ddc1c83157f545fbd3a339bc
  - name: ghcr.io/kyverno/kyvernopre
    newTag: v1.14.0@sha256:ed82d8b80e745d20f79fc0c3461f45035e19d47b9b825939d6bbcfe651adfdd4
