apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
replicas:
  - name: kyverno-admission-controller
    count: 2
images:
  - name: ghcr.io/kyverno/kyverno
    newTag: v1.12.3@sha256:1bdd02251bfa13161aa764c2fec702c9a17b8f2b2c4991b158072b1387f5ed89
  - name: ghcr.io/kyverno/kyvernopre
    newTag: v1.12.3@sha256:f2bc004824753f45a8067f425a156700cb8d0824e0cc235e9cbf673cab3b7330
