apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
replicas:
  - name: kyverno-admission-controller
    count: 2
images:
  - name: ghcr.io/kyverno/kyverno
    newTag: v1.12.4@sha256:4c9d554c0e22ff7fb4a103c78f784b28df52d305aa6b1145c5fb36e65b5a6b76
  - name: ghcr.io/kyverno/kyvernopre
    newTag: v1.12.4@sha256:9d19f8979bbb40e693029ef7a0613f5fa29112d3b95204dd83a655d41a420f3d
