apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: admission-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
replicas:
  - name: kyverno-admission-controller
    count: 2
images:
  - name: ghcr.io/kyverno/kyverno
    newTag: v1.14.3@sha256:f99822c536f18d8b4a0bdf9516d622bdd72aa03d2cda5f311c52b524816df364
  - name: ghcr.io/kyverno/kyvernopre
    newTag: v1.14.3@sha256:b8e9e32e2d5cd0f2d09ee84840e34ca9205bbc2a4af3c625d1f7b0567ab1fc2c
