apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno-background-controller
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 40%
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels: {}
                topologyKey: kubernetes.io/hostname
              weight: 1
      serviceAccountName: kyverno-background-controller
      containers:
        - name: controller
          env:
            - name: INIT_CONFIG
              value: kyverno
            - name: METRICS_CONFIG
              value: kyverno-metrics
            - name: KYVERNO_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KYVERNO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KYVERNO_SERVICEACCOUNT_NAME
              value: kyverno-background-controller
            - name: KYVERNO_DEPLOYMENT
              value: kyverno-background-controller
            - name: KYVERNO_ENABLE_TRACING
              value: "false"
          image: ghcr.io/kyverno/background-controller
          args:
            - --enableTracing=$(KYVERNO_ENABLE_TRACING)
            - --omitEvents=PolicyApplied,PolicySkipped
          ports:
            - containerPort: 9443
              name: https
              protocol: TCP
            - containerPort: 8000
              name: metrics
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
