apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: background-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: ghcr.io/kyverno/background-controller
    newTag: v1.10.1@sha256:f977f3c2c7e77b710bfa8ae4c59717c94746218a2185fc184686694f3fa6a350
