apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: cleanup-controller
  app.kubernetes.io/part-of: kyverno
resources:
  - ../../configurations/prometheus-operator
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
images:
  - name: ghcr.io/kyverno/cleanup-controller
    newTag: v1.19.1@sha256:67a48e62a8d8f8120c86914ff822b90017c54054c7b64ef8a1555645e9d9761e
