apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno-cleanup-controller
spec:
  endpoints:
    - port: metrics-port
      interval: 30s
      metricRelabelings: []
      scrapeTimeout: 25s
